name: Deploy to Production

on:
  pull_request:
    branches: [realproduction]
    types: [closed]
  workflow_dispatch:

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: realproduction
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting (warnings allowed)
      run: npm run lint || true
      
    - name: Database migrations (MANUAL ONLY)
      run: |
        echo "🚨 DATABASE MIGRATIONS MUST BE RUN MANUALLY"
        echo "💡 After deployment, run: ./scripts/deploy-migrations.sh production"
        echo "🔍 Review migrations in: supabase/migrations/"
        
    - name: Install Vercel CLI
      run: npm install -g vercel@latest
        
    - name: Deploy to Vercel (Production)
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      run: |
        vercel pull --yes --environment=production --token=$VERCEL_TOKEN
        vercel deploy --prod --token=$VERCEL_TOKEN
        
    - name: Comment on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🚀 Successfully deployed to production! Remember to run database migrations manually if needed.'
          })