name: Code Quality Check (Staging)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  quality-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting (warnings allowed)
      run: npm run lint || true
      
    - name: Build staging (validation)
      run: npm run build
      
    - name: Database migrations reminder
      run: |
        echo "📋 Code quality checks completed successfully!"
        echo "🚀 Vercel will automatically deploy this push to staging.canary.cards"
        echo "💡 Run migrations manually when needed: ./scripts/deploy-migrations.sh staging"